# shellcheck shell=bash

task.init() {
	util.symlink_or_clone 'server-deno'
	util.symlink_or_clone 'client-web'
	util.symlink_or_clone 'schema'
}

task.start() {
	code './pansophiae.code-workspace'
}

task.cp() {
	# TODO
	cp ./repos/schema/src/index.ts ./repos/client-web/src/schema.ts
	cp ./repos/schema/src/index.ts ./repos/server-deno/src/schema.ts
	c0=$(cat ./repos/client-web/src/schema.ts)
	echo -e "// THIS FILE IS AUTOGENERATED\n$c0" > ./repos/client-web/src/schema.ts
	c1=$(cat ./repos/server-deno/src/schema.ts)ma
	echo -e "// THIS FILE IS AUTOGENERATED\n$c1" > ./repos/server-deno/src/schema.ts
}

util.symlink_or_clone() {
	local repo_name="$1"

	if [ -d "$BAKE_ROOT/../$repo_name" ]; then
		bake.info "Symlinking $repo_name"

		mkdir -p './repos'
		ln -Tsf "$BAKE_ROOT/../$repo_name" "./repos/$repo_name"
	else
		bake.info "Cloning $repo_name"
		
		git clone "git@github.com:pansophiae/$repo_name" "./repos/$repo_name"
	fi
}